apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-guidellm

resources:
  - namespace.yaml
  - pvc.yaml
  - gm-gptoss-pvc-job.yaml
  # - pvc-reader.yaml
  # - gm-job.yaml
  # - gm-llama-job.yaml
  # - gm-llama-job-pvc.yaml
